src/book_shop_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "book_shop"

urlpatterns = [
    path('first-page/', views.FirstPageList.as_view(), name="first-page"),
    path('search/', views.search, name='search'),    
    path('book-list/', views.BookList.as_view(), name="book-list"),
    path('book-detail/<int:pk>/', views.BookListDetail.as_view(), name="book-detail"),
    path('book-create/', views.BookCreate.as_view(), name="book-create"),
    path('book-update/<int:pk>/', views.BookUpdate.as_view(), name="book-update"),
    path('book-delete/<int:pk>/', views.BookDelete.as_view(), name="book-delete"),
    path('author-list/', views.AuthorList.as_view(), name="author-list"),
    path('author-detail/<int:pk>/', views.AuthorListDetail.as_view(), name="author-detail"),
    path('author-create/', views.AuthorCreate.as_view(), name="author-create"),
    path('author-update/<int:pk>/', views.AuthorUpdate.as_view(), name="author-update"),
    path('author-delete/<int:pk>/', views.AuthorDelete.as_view(), name="author-delete"),
    path('series-list/', views.SeriesList.as_view(), name="series-list"),
    path('series-detail/<int:pk>/', views.SeriesListDetail.as_view(), name="series-detail"),
    path('series-create/', views.SeriesCreate.as_view(), name="series-create"),
    path('series-update/<int:pk>/', views.SeriesUpdate.as_view(), name="series-update"),
    path('series-delete/<int:pk>/', views.SeriesDelete.as_view(), name="series-delete"),
    path('genre-list/', views.GenreList.as_view(), name="genre-list"),
    path('genre-detail/<int:pk>/', views.GenreListDetail.as_view(), name="genre-detail"),
    path('genre-create/', views.GenreCreate.as_view(), name="genre-create"),
    path('genre-update/<int:pk>/', views.GenreUpdate.as_view(), name="genre-update"),
    path('genre-delete/<int:pk>/', views.GenreDelete.as_view(), name="genre-delete"),
    path('publisher-list/', views.PublisherList.as_view(), name="publisher-list"),
    path('publisher-detail/<int:pk>/', views.PublisherListDetail.as_view(), name="publisher-detail"),
    path('publisher-create/', views.PublisherCreate.as_view(), name="publisher-create"),
    path('publisher-update/<int:pk>/', views.PublisherUpdate.as_view(), name="publisher-update"),
    path('publisher-delete/<int:pk>/', views.PublisherDelete.as_view(), name="publisher-delete"),
]

src/orders/urls.py
from django.urls import path, include
from . import views
from .views import order_status_list

app_name = "orders"

urlpatterns = [  
    path("cart/", views.view_cart, name="view-cart"),
    path("cart-order-list/", views.view_order_cart, name="cart-order-list"),
    path("add-item/", views.add_item_to_cart_view, name="add-item-to-cart"),
    path("evaluate/", views.evaluate_cart, name="evaluate-cart"),
    path("order-create/", views.CreateOrderGoodsView.as_view(), name="view-order-create"),
    path("created-page/", views.OrderGoodsCreateView.as_view(), name="created-page"),
    path("created-new/", views.OrderGoodsCreateViewNew.as_view(), name="created-new"),
    path('order-goods-list/', views.OrderGoodsList.as_view(), name="order-goods-list"),
    path('order-goods-update/<int:pk>/', views.OrderGoodsUpdate.as_view(), name="order-goods-update"),
    path('orderdoods-detail/<int:pk>/', views.OrderGoodsListDetail.as_view(), name="orderdoods-detail"),
    path('orderdoods-delete/<int:pk>/', views.OrderGoodsDelete.as_view(), name="orderdoods-delete"),
    path('item-in-cart-list/', views.ItemInCartList.as_view(), name="item-in-cart-list"),
    path('item-in-cart-detail/<int:pk>/', views.ItemInCartDetail.as_view(), name="item-in-cart-detail"),
    path('item-in-cart-delete/<int:pk>/', views.ItemInCartDelete.as_view(), name="item-in-cart-delete"),
    path('cart-list/', views.CartList.as_view(), name="cart-list"),
    path('cart-list-detail/<int:pk>/', views.CartListDetail.as_view(), name="cart-list-detail"),
    path('order-status/', order_status_list, name='order-status'),
    path('order-status-list/', views.OrderStatusList.as_view(), name="order-status-list"),
    path('order-status-detail/<int:pk>/', views.OrderStatusDetail.as_view(), name="order-status-detail"),
    path('order-status-create/', views.OrderStatusCreate.as_view(), name="order-status-create"),
    path('order-status-update/<int:pk>/', views.OrderStatusUpdate.as_view(), name="order-status-update"),
    path('order-status-delete/<int:pk>/', views.OrderStatusDelete.as_view(), name="order-status-delete"),
    ]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('book_shop/', include('book_shop_app.urls', namespace='book_shop')),
    path('user/', include('user_app.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('review/', include('review.urls', namespace='review')),    
]

# не для хостинга
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/review/urls.py
from django.urls import path, include
from . views import book_detail
from . import views

app_name = "review"

urlpatterns = [  
    path('book/<int:book_id>/', book_detail, name='book-detail'),
    path('review-list/', views.ReviewList.as_view(), name="review-list"),
    path('review-delete/<int:pk>/', views.ReviewDelete.as_view(), name="review-delete"),
]

src/user_app/urls.py
from django.urls import path, include
from . import views
from . views import registration, login_view, logout_view

app_name = "user"

urlpatterns = [  
    path("login_entrance/", login_view, name="login_entrance"),
    path("logout/", logout_view, name="logout"),
    path('registration/', registration, name="registration"), 
    path('login/', views.MyLoginView.as_view(), name="login"),
    path("personal-page-list/", views.PersonalPageList.as_view(), name="personal-page-list"), 
    path('profile-detail/', views.CustomerDetail.as_view(), name="profile-detail"), 
    path('profile-create/', views.CustomerCreate.as_view(), name="profile-create"),
    path('profile-update/<int:pk>/', views.CustomerUpdate.as_view(), name="profile-update"),
]

src/templates/auth_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100" data-bs-theme="auto">
<head>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
  
        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }
  
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
  
        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }
  
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
  
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
  
        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
  
          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }
  
        .bd-mode-toggle {
          z-index: 1500;
        }
  
        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
      </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static "/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <title>{{ page_title }}</title>
    <link href="{% static "/custom_css/sticky-footer-navbar.css" %}" rel="stylesheet">
</head>
<body class="d-flex flex-column h-100">
 
    
    <main class="flex-shrink-0">
        <div class="container">

            {% block MAIN_CONTENT %}{% endblock MAIN_CONTENT %}

        </div>
      </main>
      
<script src="{% static "/bootstrap/js/bootstrap.bundle.min.js" %}"></script>        
</body>
</html>

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100" data-bs-theme="auto">
<head>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
  
        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }
  
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
  
        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }
  
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
  
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
  
        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
  
          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }
  
        .bd-mode-toggle {
          z-index: 1500;
        }
  
        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
      </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static "/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <title>{{ page_title }}</title>
    <link href="{% static "/custom_css/sticky-footer-navbar.css" %}" rel="stylesheet">
</head>
<body class="d-flex flex-column h-100">
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'book_shop:first-page' %}">Vitrina.by</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'book_shop:book-list' %}">Книги</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'book_shop:author-list' %}">Авторы</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'book_shop:genre-list' %}">Жанры</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'book_shop:publisher-list' %}">Издательства</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'book_shop:series-list' %}">Серии</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'orders:view-cart' %}">Корзина</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'user:personal-page-list' %}">Личный кабинет</a>
                </li>
                {% load group_tags %}
                {% if user.is_authenticated %}
                    {% if user|has_group:"Managers" %}
                    <li class="nav-item">
                    <a class="nav-link active" href="{% url 'orders:item-in-cart-list' %}">Корзинки покупателей</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" href="{% url 'orders:order-goods-list' %}">Обработка заказов</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active" href="{% url 'orders:order-status-list' %}">Обработка статусов</a>
                        </li>
                    <li class="nav-item">
                    <a class="nav-link active" href="{% url 'review:review-list' %}">Обработка отзывов</a>
                    {% else %}
                    {% endif %}
                {% endif %}
                </li>             
              </ul>               
                <button class="btn btn-outline-success" type="button"><a href="{% url 'book_shop:search' %}">Поиск книг</a></button>
              
            </div>
          </div>
        </nav>
    


    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check2" viewBox="0 0 16 16">
          <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
        </symbol>
        <symbol id="circle-half" viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
        </symbol>
        <symbol id="moon-stars-fill" viewBox="0 0 16 16">
          <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
          <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
        </symbol>
        <symbol id="sun-fill" viewBox="0 0 16 16">
          <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
        </symbol>
      </svg>

    </header>
    <main class="flex-shrink-0">


        <div class="container">

            {% block MAIN_CONTENT %}{% endblock MAIN_CONTENT %}

        </div>


      </main>

    <h1></h1>
  

<footer class="footer mt-auto py-3 bg-body-tertiary">
    <div class="container">
      <span class="text-body-secondary">© 2024 Книжный магазин - Витрина. Все права защищены.</span>
    </div>
  </footer>

<script src="{% static "/bootstrap/js/bootstrap.bundle.min.js" %}"></script>        
</body>
</html>