src/book_shop_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "book_shop"

urlpatterns = [
    path('first-page/', views.FirstPageList.as_view(), name="first-page"),
    path('search/', views.search, name='search'),    
    path('book-list/', views.BookList.as_view(), name="book-list"),
    path('book-detail/<int:pk>/', views.BookListDetail.as_view(), name="book-detail"),
    path('book-create/', views.BookCreate.as_view(), name="book-create"),
    path('book-update/<int:pk>/', views.BookUpdate.as_view(), name="book-update"),
    path('book-delete/<int:pk>/', views.BookDelete.as_view(), name="book-delete"),
    path('author-list/', views.AuthorList.as_view(), name="author-list"),
    path('author-detail/<int:pk>/', views.AuthorListDetail.as_view(), name="author-detail"),
    path('author-create/', views.AuthorCreate.as_view(), name="author-create"),
    path('author-update/<int:pk>/', views.AuthorUpdate.as_view(), name="author-update"),
    path('author-delete/<int:pk>/', views.AuthorDelete.as_view(), name="author-delete"),
    path('series-list/', views.SeriesList.as_view(), name="series-list"),
    path('series-detail/<int:pk>/', views.SeriesListDetail.as_view(), name="series-detail"),
    path('series-create/', views.SeriesCreate.as_view(), name="series-create"),
    path('series-update/<int:pk>/', views.SeriesUpdate.as_view(), name="series-update"),
    path('series-delete/<int:pk>/', views.SeriesDelete.as_view(), name="series-delete"),
    path('genre-list/', views.GenreList.as_view(), name="genre-list"),
    path('genre-detail/<int:pk>/', views.GenreListDetail.as_view(), name="genre-detail"),
    path('genre-create/', views.GenreCreate.as_view(), name="genre-create"),
    path('genre-update/<int:pk>/', views.GenreUpdate.as_view(), name="genre-update"),
    path('genre-delete/<int:pk>/', views.GenreDelete.as_view(), name="genre-delete"),
    path('publisher-list/', views.PublisherList.as_view(), name="publisher-list"),
    path('publisher-detail/<int:pk>/', views.PublisherListDetail.as_view(), name="publisher-detail"),
    path('publisher-create/', views.PublisherCreate.as_view(), name="publisher-create"),
    path('publisher-update/<int:pk>/', views.PublisherUpdate.as_view(), name="publisher-update"),
    path('publisher-delete/<int:pk>/', views.PublisherDelete.as_view(), name="publisher-delete"),
]

src/orders/urls.py
from django.urls import path, include
from . import views
from .views import order_status_list

app_name = "orders"

urlpatterns = [  
    path("cart/", views.view_cart, name="view-cart"),
    path("cart-order-list/", views.view_order_cart, name="cart-order-list"),
    path("add-item/", views.add_item_to_cart_view, name="add-item-to-cart"),
    path("evaluate/", views.evaluate_cart, name="evaluate-cart"),
    path("order-create/", views.CreateOrderGoodsView.as_view(), name="view-order-create"),
    path("created-page/", views.OrderGoodsCreateView.as_view(), name="created-page"),
    path("created-new/", views.OrderGoodsCreateViewNew.as_view(), name="created-new"),
    path('order-goods-list/', views.OrderGoodsList.as_view(), name="order-goods-list"),
    path('order-goods-update/<int:pk>/', views.OrderGoodsUpdate.as_view(), name="order-goods-update"),
    path('orderdoods-detail/<int:pk>/', views.OrderGoodsListDetail.as_view(), name="orderdoods-detail"),
    path('orderdoods-delete/<int:pk>/', views.OrderGoodsDelete.as_view(), name="orderdoods-delete"),
    path('item-in-cart-list/', views.ItemInCartList.as_view(), name="item-in-cart-list"),
    path('item-in-cart-detail/<int:pk>/', views.ItemInCartDetail.as_view(), name="item-in-cart-detail"),
    path('item-in-cart-delete/<int:pk>/', views.ItemInCartDelete.as_view(), name="item-in-cart-delete"),
    path('cart-list/', views.CartList.as_view(), name="cart-list"),
    path('cart-list-detail/<int:pk>/', views.CartListDetail.as_view(), name="cart-list-detail"),
    path('order-status/', order_status_list, name='order-status'),
    path('order-status-list/', views.OrderStatusList.as_view(), name="order-status-list"),
    path('order-status-detail/<int:pk>/', views.OrderStatusDetail.as_view(), name="order-status-detail"),
    path('order-status-create/', views.OrderStatusCreate.as_view(), name="order-status-create"),
    path('order-status-update/<int:pk>/', views.OrderStatusUpdate.as_view(), name="order-status-update"),
    path('order-status-delete/<int:pk>/', views.OrderStatusDelete.as_view(), name="order-status-delete"),
    ]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('book_shop/', include('book_shop_app.urls', namespace='book_shop')),
    path('user/', include('user_app.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('review/', include('review.urls', namespace='review')),    
]

# не для хостинга
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user_app/urls.py
from django.urls import path, include
from . import views
from . views import registration, login_view, logout_view

app_name = "user"

urlpatterns = [  
    path("login_entrance/", login_view, name="login_entrance"),
    path("logout/", logout_view, name="logout"),
    path('registration/', registration, name="registration"), 
    path('login/', views.MyLoginView.as_view(), name="login"),
    path("personal-page-list/", views.PersonalPageList.as_view(), name="personal-page-list"), 
    path('profile-detail/', views.CustomerDetail.as_view(), name="profile-detail"), 
    path('profile-create/', views.CustomerCreate.as_view(), name="profile-create"),
    path('profile-update/<int:pk>/', views.CustomerUpdate.as_view(), name="profile-update"),
]

src/book_shop_app/forms.py
from django import forms
from . import models


class BookCreateForm(forms.ModelForm):
      
    class Meta:
        model = models.Book
        fields = ['title', 'cover', 'price', 'author', 'series', 'genre', 'publication_year', 'pages',
           'binding', 'format', 'isbn', 'weight', 'age_restrictions',
           'publisher', 'quantity_in_stock', 'is_active', 'rating',]
    
        


















    # title = forms.CharField(max_length=200, required=True, label='Название',)
    # cover = forms.ImageField(required=True, label='Обложка',)
    # price = forms.DecimalField(max_digits=10, decimal_places=2, required=True, label='Цена',)
    # author = forms.CharField(required=True, label='Автор', )
    # series = forms.CharField(required=True, label='Серия',)
    # genre = forms.CharField(required=True, label='Жанр',)
    # publication_year = forms.CharField(required=True, label='Год издания',)
    # pages = forms.CharField(required=True, label='Количество страниц',)
    # binding = forms.CharField(max_length=50, required=True, label='Переплет',)
    # format = forms.CharField(max_length=50, required=True, label='Формат',)
    # isbn = forms.CharField(max_length=13, required=True, label='ISBN',)
    # weight = forms.FloatField(required=True, label='Вес книги',)
    # age_restrictions = forms.CharField(max_length=50, required=True, label='Возврастные ограничения',)
    # publisher = forms.CharField(required=True, label='Издательство',)
    # quantity_in_stock = forms.CharField(required=True, label='Количество книг в наличии',)
    # is_active = forms.BooleanField(required=True, label='Доступен для заказа',)
    # rating = forms.FloatField(required=True, label='Рейтинг книги',)

src/book_shop_app/views.py
from typing import Any
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from . import models, forms, utils
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from .models import Book


def search(request):
    query = request.GET.get('q')
    book = models.Book.objects
    books = []
    if query:
        books = Book.objects.filter(title__icontains=query)  # Поиск по названию
    return render(request, 'book_shop_app/search_results.html', {'books': books, 'query': book})



class BookList(generic.ListView):
    model = models.Book
    paginate_by = 5

class BookListDetail(generic.DetailView):
    model = models.Book

class BookCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    permission_required = 'book_shop_app.add_book'
    login_url = reverse_lazy('user:login')
    model = models.Book
    form_class = forms.BookCreateForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Создание новой книги:"
        return context


class BookUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    permission_required = 'book_shop_app.change_book'
    login_url = reverse_lazy('user:login')
    model = models.Book
    fields = ['title', 'cover', 'price', 'author', 'series', 'genre', 'publication_year', 'pages',
              'binding', 'format', 'isbn', 'weight', 'age_restrictions',
              'publisher', 'quantity_in_stock', 'is_active', 'rating',]

class BookDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    permission_required = 'book_shop_app.delete_book'
    login_url = reverse_lazy('user:login')
    model = models.Book
    success_url = reverse_lazy('book_shop:book-list')






class AuthorList(generic.ListView): 
    model = models.Author
    paginate_by = 10

class AuthorListDetail(generic.DetailView): 
    model = models.Author

class AuthorCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    permission_required = 'book_shop_app.add_author' 
    login_url = reverse_lazy('user:login')
    model = models.Author
    
    fields = ['name', 'bio',]

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Создание нового автора:"
        return context

class AuthorUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    permission_required = 'book_shop_app.change_author'
    login_url = reverse_lazy('user:login')
    model = models.Author
    fields = ['name', 'bio',]

class AuthorDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    permission_required = 'book_shop_app.delete_author'
    login_url = reverse_lazy('user:login')
    model = models.Author
    success_url = reverse_lazy('book_shop:author-list')








class SeriesList(generic.ListView):   
    model = models.Series
    paginate_by = 10

class SeriesListDetail(generic.DetailView):    
    model = models.Series

class SeriesCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    permission_required = 'book_shop_app.add_series'
    login_url = reverse_lazy('user:login')
    model = models.Series
    fields = ['title', 'description',]
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Создание новой серии:"
        return context

class SeriesUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    permission_required = 'book_shop_app.change_series'
    login_url = reverse_lazy('user:login')
    model = models.Series
    fields = ['title', 'description',]

class SeriesDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    permission_required = 'book_shop_app.delete_series'
    login_url = reverse_lazy('user:login')
    model = models.Series
    success_url = reverse_lazy('book_shop:series-list')









class GenreList(generic.ListView):   
    model = models.Genre
    paginate_by = 10

class GenreListDetail(generic.DetailView):   
    model = models.Genre

class GenreCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    permission_required = 'book_shop_app.add_genre'
    login_url = reverse_lazy('user:login')
    model = models.Genre
    fields = ['name',]
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Создание нового жанра:"
        return context

class GenreUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    permission_required = 'book_shop_app.change_genre'
    login_url = reverse_lazy('user:login')
    model = models.Genre
    fields = ['name',]

class GenreDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    permission_required = 'book_shop_app.delete_genre'
    login_url = reverse_lazy('user:login')
    model = models.Genre
    success_url = reverse_lazy('book_shop:genre-list')









class PublisherList(generic.ListView):    
    model = models.Publisher
    paginate_by = 10

class PublisherListDetail(generic.DetailView):    
    model = models.Publisher

class PublisherCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    permission_required = 'book_shop_app.add_publisher'
    login_url = reverse_lazy('user:login')
    model = models.Publisher
    fields = ['name', 'address', 'website',]
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Создание нового издательства:"
        return context

class PublisherUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    permission_required = 'book_shop_app.change_publisher'
    login_url = reverse_lazy('user:login')
    model = models.Publisher
    fields = ['name', 'address', 'website',]

class PublisherDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    permission_required = 'book_shop_app.delete_publisher'
    login_url = reverse_lazy('user:login')
    model = models.Publisher
    success_url = reverse_lazy('book_shop:publisher-list')

class FirstPageList(generic.ListView):
    model = models.FirstPage
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['newest'] = get_item_for_today(self.request)
        # context['sale'] = get_item_on_sale(self.request)
        # context['top'] = get_top_item(self.request)
        return context

src/book_shop_app/templates/book_shop_app/author_detail.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}
<h1>Автор {{object.id}}</h1>
<ul>
    <li><b>ФИО автора</b>: {{ object.name }}</li>
    <li><b>Биография</b>: {{ object.bio }}</li>
</ul>

{% if object.authors.all %}
    <h2>Книги автора:</h2>
    {% for book in object.authors.all %}
        <ul>
            <li>{{ book.title }}</li>
        </ul>     
    {% endfor %}
{% else %}
<h3>Нет книг у автора</h3>

{% endif %}

                
{% endblock MAIN_CONTENT %}

src/book_shop_app/templates/book_shop_app/author_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block MAIN_CONTENT %}

{% if user.is_authenticated %}

    <h1>{{ page_title }}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }} 
    <button type="submit" class="btn btn-outline-primary">Сохранить</button>

    </form>   
{% endif %}         
{% endblock MAIN_CONTENT %}

src/book_shop_app/templates/book_shop_app/author_list.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}
<br>
<br>
{% load group_tags %}
{% if user.is_authenticated %}
    {% if user|has_group:"Managers" %}
        <h4><a href="{% url 'book_shop:author-create' %}">Добавить автора</a></h4>  
    {% else %}
        <p>Вы авторизованный пользователь</p>
    {% endif %}
{% else %}
<p>Вы не авторизованный пользователь</p>
{% endif %}

<br>
<br>
<h5>Все авторы:</h5>


    <table class="table table-striped">
        <tr>
            <th>IDномер</th>
            <th>ФИО</th>
            <th>Книги автора</th>
            {% if user.is_authenticated %}
                {% if user|has_group:"Managers" %}
                <th>Редактор</th> 
                <th>Удаление</th>  
                {% else %}
                    
            {% endif %}
            {% endif %}

        </tr>
        {% for obj in page_obj %}
        <tr>
            <th>{{ obj.id }}</th>
            <th>{{ obj.name }}</th>
            <th><button type="button" class="btn btn-outline-info"><a href="{% url 'book_shop:author-detail' obj.id %}">Информация</a></button></th>
            {% if user.is_authenticated %}
                {% if user|has_group:"Managers" %}
            <th><button type="button" class="btn btn-outline-success"><a href="{% url 'book_shop:author-update' obj.id %}">Изменить</a></button></th>
            <th><button type="button" class="btn btn-outline-danger"><a href="{% url 'book_shop:author-delete' obj.id %}">Удалить</a></button></th> 
            {% else %}
                    
            {% endif %}
            {% endif %}
        </tr>
        {% endfor %}
    </table>

    
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; первый</a>
                <a href="?page={{ page_obj.previous_page_number }}">предыдущий</a>
            {% endif %}
    
            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">следующий</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">последний &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock MAIN_CONTENT %}

src/book_shop_app/templates/book_shop_app/book_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block MAIN_CONTENT %}


<h1 class="mt-5">{{ page_title }}</h1>
  <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }} 
            <button type="submit" class="btn btn-outline-primary">Сохранить</button>   

    </form> 
               
{% endblock MAIN_CONTENT %}

src/book_shop_app/templates/book_shop_app/book_list.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}
<br>
<br>
{% load group_tags %}
{% if user.is_authenticated %}
    {% if user|has_group:"Managers" %}
    <h4><a href="{% url 'book_shop:book-create' %}">Добавить новую книгу</a></h4>  
    {% else %}
        <p>Вы авторизованный пользователь</p>
    {% endif %}
{% else %}
<p>Вы не авторизованный пользователь</p>
{% endif %}
       
<br>
<h5>Каталог книг:</h5>
    
    <table class="table table-striped">
        <tr>
            <th><center>Обложка</center></th>
            <th><center>Название</center></th>
            <th><center>Артикул</center></th>
            <th><center>Количество книг<br> в наличии</center></th>
            <th><center>Цена</center></th>
            <th><center>Рейтинг</center></th>
            <th><center>Навигация</center></th>
            
        </tr>
        {% for obj in page_obj %}
        <tr>
            <th><center><img src="{{ obj.cover.url }}" class="img-thumbnail" alt=""></center></th>
            <th><center>{{ obj.title }}</center></th>
            <th><center>{{ obj.id }}</center></th>
            <th><center>{{ obj.quantity_in_stock }}</center></th>
            <th><center>{{ obj.price }} BYN</center></th>
            <th><center>{{ obj.rating }}</center></th>
            <th>   
                <div class="mb-1">   
            <button type="button" class="btn btn-outline-info"><a href="{% url 'book_shop:book-detail' obj.id %}">Подробности</a></button>
            <button type="button" class="btn btn-outline-info"><a href="{% url 'review:book-detail' obj.id %}">Отзывы</a></button><br>
                </div>

            {% if user.is_authenticated %}
                {% if user|has_group:"Managers" %}
                <div class="mb-1">
                <button type="button" class="btn btn-outline-success"><a href="{% url 'book_shop:book-update' obj.id %}">Изменить</a></button>
                <button type="button" class="btn btn-outline-danger"><a href="{% url 'book_shop:book-delete' obj.id %}">Удалить</a></button><br>
                </div>
                
                {% else %}
                    
                {% endif %}
            {% endif %}

            <form action="{% url "orders:add-item-to-cart" %}" method="post">
                {% csrf_token %}
            <input type="hidden" name="item_id" value="{{ obj.id }}">
            <div class="mb-1">
                <label class="form-label">Выбрать</label>      
                <input type="number" required pattern name="quantity" placeholder="Количество:" class="form-control" step="1" min="1">         
              </div>
              <button type="submit" class="btn btn-outline-danger">В корзину</button>
            </form>
            <p>
            </th>


            
        </tr>
        {% endfor %}
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; первый</a>
                <a href="?page={{ page_obj.previous_page_number }}">предыдущий</a>
            {% endif %}
    
            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">следующий</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">последний &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock MAIN_CONTENT %}  





    {% comment %} <table class="table table-striped">
        <tr>
            <th></th>
            <th>Книга</th>
            <th>Портфолио</th>
            {% if user.is_authenticated %}
                {% if user|has_group:"Managers" %}
                <th>Редактор</th>
                <th>Удаление</th>
                {% else %}
                    
            {% endif %}
            {% endif %}

        </tr>
        {% for obj in object_list %}
        <tr>
            <th><img src="{{ obj.cover.url }}" class="img-thumbnail" alt=""></th>
            <th>{{ obj.title }}</th>
            <th><button type="button" class="btn btn-outline-info"><a href="{% url 'book_shop:book-detail' obj.id %}">Информация</a></button></th>
            {% if user.is_authenticated %}
                {% if user|has_group:"Managers" %}
            <th><button type="button" class="btn btn-outline-success"><a href="{% url 'book_shop:book-update' obj.id %}">Изменить</a></button></th>
            <th><button type="button" class="btn btn-outline-danger"><a href="{% url 'book_shop:book-delete' obj.id %}">Удалить</a></button></th> 
                {% else %}
                    
                {% endif %}
            {% endif %}
        </tr>
        {% endfor %}
    </table> {% endcomment %}

src/book_shop_app/templates/book_shop_app/firstpage_list.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}

<div class="header-container">
    <div class="top-link">
        <div class="container">
            <div class="row-fluid">
                <div class="logo-container span2">
                    <br>
                    <span class="logo"><strong><h3>Vitrina.by - книжный Интернет-магазин в Минске с доставкой по всей Беларуси</h3></strong></span>
                    
                </div>
                <div class="span15 link-left">                   
                    <ul class="phones">
                    <li>&#9990 A1:<span class="phone-number desktop">+375 29 123 45 67</span></li>
                    <li>&#9990 МТС: <span class="phone-number desktop">+375 33 123 45 67</span></li>
                    <li>&#9990 Life: <span class="phone-number desktop">+375 25 123 45 67</span></li>
                    </ul>                
                </div>
                    <div class="span14 link-right">
                        <ul class="links">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'user:logout' %}">Выход из профиля</a></li>
                        {% else %}
                        <li><a href="{% url 'user:registration' %}">Регистрация нового пользователя</a></li>
                        <li><a href="{% url 'user:login_entrance' %}">Войти в свой профиль</a></li>
                        {% endif %}
                        <br>
                        <li><a href="{% url 'orders:view-cart' %}">Моя корзина</a></li>
                        <li><a href="{% url 'book_shop:search' %}">Поиск книг</a></li>
                        </ul>
                            <div class="welcome-msg">Вы наконец заглянули к нам в поисках доброй пары-тройки книг? Мы бесконечно рады! 
                                Приветствуем, дорогой читатель, в книжном интернет-магазине vitrina.by.
                                У нас для вас много книг. Для самых разных людей.</div>
                    </div>
            </div>
        </div>
    </div>

    <div>
        <br>
        <span class="logo"><strong><h2><font color='blue'>Наши подборки для вас:</font></h2></strong></span>
        <br>        
        {% load group_tags %}
        <span class="logo"><strong><h3><font color='red'>Новинки книг!</font></h3></strong></span>       
            {% newest_items %}    
        <br>     
        <br>
        <span class="logo"><strong><h3><font color='red'>Старинные книги!</font></h3></strong></span>  
            {% oldest_items %}
    </div>    

</div>


{% endblock MAIN_CONTENT %}

src/book_shop_app/templates/book_shop_app/genre_confirm_delete.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}

<h1>Вы действительно хотите удалить объект: {{ object }}?</h1>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-danger">Удалить!!!</button>
    
</form>
                
{% endblock MAIN_CONTENT %}

src/book_shop_app/templates/book_shop_app/publisher_confirm_delete.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}

<h1>Вы действительно хотите удалить объект: {{ object }}?</h1>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-danger">Удалить!!!</button>
    
</form>
                
{% endblock MAIN_CONTENT %}

src/book_shop_app/templates/book_shop_app/publisher_list.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}
<br>
<br>
{% load group_tags %}
{% if user.is_authenticated %}
    {% if user|has_group:"Managers" %}
    <h4><a href="{% url 'book_shop:publisher-create' %}">Добавить новое издательство</a></h4>
    {% else %}
        <p>Вы авторизованный пользователь</p>
    {% endif %}
{% else %}
<p>Вы не авторизованный пользователь</p>
{% endif %}

<br>
<br>
<h5>Все издательства:</h5>

    <table class="table table-striped">
        <tr>
            <th>IDномер</th>
            <th>Издательство</th>
            <th>Подробности</th>
            {% if user.is_authenticated %}
                {% if user|has_group:"Managers" %}
                <th>Редактор</th>
                <th>Удаление</th>
                {% else %}
                    
            {% endif %}
            {% endif %}

        </tr>
        {% for obj in page_obj %}
        <tr>
            <th>{{ obj.id }}</th>
            <th>{{ obj.name }}</th>
            <th><button type="button" class="btn btn-outline-info"><a href="{% url 'book_shop:publisher-detail' obj.id %}">Информация</a></button></th>
            {% if user.is_authenticated %}
                {% if user|has_group:"Managers" %}
            <th><button type="button" class="btn btn-outline-success"><a href="{% url 'book_shop:publisher-update' obj.id %}">Изменить</a></button></th>
            <th><button type="button" class="btn btn-outline-danger"><a href="{% url 'book_shop:publisher-delete' obj.id %}">Удалить</a></button></th> 
                {% else %}
                    
                {% endif %}
            {% endif %}
        </tr>
        {% endfor %}
    </table>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; первый</a>
                <a href="?page={{ page_obj.previous_page_number }}">предыдущий</a>
            {% endif %}
    
            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">следующий</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">последний &raquo;</a>
            {% endif %}
        </span>
    </div>               
{% endblock MAIN_CONTENT %}