src/orders/urls.py
from django.urls import path, include
from . import views
from .views import order_status_list

app_name = "orders"

urlpatterns = [  
    path("cart/", views.view_cart, name="view-cart"),
    path("cart-order-list/", views.view_order_cart, name="cart-order-list"),
    path("add-item/", views.add_item_to_cart_view, name="add-item-to-cart"),
    path("evaluate/", views.evaluate_cart, name="evaluate-cart"),
    path("order-create/", views.CreateOrderGoodsView.as_view(), name="view-order-create"),
    path("created-page/", views.OrderGoodsCreateView.as_view(), name="created-page"),
    path("created-new/", views.OrderGoodsCreateViewNew.as_view(), name="created-new"),
    path('order-goods-list/', views.OrderGoodsList.as_view(), name="order-goods-list"),
    path('order-goods-update/<int:pk>/', views.OrderGoodsUpdate.as_view(), name="order-goods-update"),
    path('orderdoods-detail/<int:pk>/', views.OrderGoodsListDetail.as_view(), name="orderdoods-detail"),
    path('orderdoods-delete/<int:pk>/', views.OrderGoodsDelete.as_view(), name="orderdoods-delete"),
    path('item-in-cart-list/', views.ItemInCartList.as_view(), name="item-in-cart-list"),
    path('item-in-cart-detail/<int:pk>/', views.ItemInCartDetail.as_view(), name="item-in-cart-detail"),
    path('item-in-cart-delete/<int:pk>/', views.ItemInCartDelete.as_view(), name="item-in-cart-delete"),
    path('cart-list/', views.CartList.as_view(), name="cart-list"),
    path('cart-list-detail/<int:pk>/', views.CartListDetail.as_view(), name="cart-list-detail"),
    path('order-status/', order_status_list, name='order-status'),
    path('order-status-list/', views.OrderStatusList.as_view(), name="order-status-list"),
    path('order-status-detail/<int:pk>/', views.OrderStatusDetail.as_view(), name="order-status-detail"),
    path('order-status-create/', views.OrderStatusCreate.as_view(), name="order-status-create"),
    path('order-status-update/<int:pk>/', views.OrderStatusUpdate.as_view(), name="order-status-update"),
    path('order-status-delete/<int:pk>/', views.OrderStatusDelete.as_view(), name="order-status-delete"),
    ]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('book_shop/', include('book_shop_app.urls', namespace='book_shop')),
    path('user/', include('user_app.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('review/', include('review.urls', namespace='review')),    
]

# не для хостинга
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user_app/urls.py
from django.urls import path, include
from . import views
from . views import registration, login_view, logout_view

app_name = "user"

urlpatterns = [  
    path("login_entrance/", login_view, name="login_entrance"),
    path("logout/", logout_view, name="logout"),
    path('registration/', registration, name="registration"), 
    path('login/', views.MyLoginView.as_view(), name="login"),
    path("personal-page-list/", views.PersonalPageList.as_view(), name="personal-page-list"), 
    path('profile-detail/', views.CustomerDetail.as_view(), name="profile-detail"), 
    path('profile-create/', views.CustomerCreate.as_view(), name="profile-create"),
    path('profile-update/<int:pk>/', views.CustomerUpdate.as_view(), name="profile-update"),
]

src/user_app/models.py
from django.urls import reverse, reverse_lazy
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model # вместо user

User = get_user_model()
class Customer(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone = models.CharField(max_length=15, blank=True)
    address = models.TextField(max_length=300, null=True)
    additional_info = models.TextField(blank=True)
    # Поле для группы, которое не доступно к редактированию
    GROUP_CHOICES = [
        ('regular', 'Обычный покупатель'),
        ('vip', 'VIP покупатель'),
    ]
    group = models.CharField(max_length=10, choices=GROUP_CHOICES, default='regular')
    
    def __str__(self):
        return f"{self.user}"
    
    

class PersonalPage(models.Model):
    pass

src/user_app/forms.py
from django import forms
from . import models



class CustomerCreateForm(forms.ModelForm):
    email = forms.CharField(
        required=True,
        label='Электронная почта',)
    first_name = forms.CharField(
        max_length=30,
        required=True,
        label='Имя')
    last_name = forms.CharField(
        max_length=30,
        required=True,
        label='Фамилия')
    phone = forms.CharField(
        max_length=15,
        label='Телефон')
    address = forms.CharField(
        required=True,
        label='Адрес доставки')
    additional_info = forms.CharField(
        label='Дополнительная информация',
        widget=forms.Textarea)

    class Meta:
        model = models.Customer
        fields = ['email', 'first_name', 'last_name', 'phone',
              'address', 'additional_info', ]
        

src/user_app/views.py
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http.response import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from . import models, forms

from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Вы вошли как {username}.")
                return redirect(reverse_lazy('user:profile-detail'))
            else:
                messages.error(request, "Неправильное имя пользователя или пароль.")
        else:
            messages.error(request, "Неправильное имя пользователя или пароль.")
            messages.error(request, "Пройдите регистрацию или продолжите как не зарегистрированный пользователь.")
    form = AuthenticationForm()
    return render(request = request,
                  template_name = "user_app/login_entrance.html",
                  context={"form":form})



def logout_view(request):
    logout(request)
    messages.info(request, "Вы вышли из системы.")
    return redirect((reverse_lazy('user:personal-page-list')))




def registration(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # получаем имя пользователя и пароль из формы
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            # выполняем аутентификацию
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(reverse_lazy('user:profile-create'))
    else:
        form = UserCreationForm()
    return render(request, 'user_app/registration.html', {'form': form})



class PersonalPageList(generic.ListView):
    model = models.PersonalPage


class MyLoginView(auth_views.LoginView):
    template_name = "user_app/login.html"
   


class CheckProfileMixin(LoginRequiredMixin):
    redirect_on_missing_profile = True
    def dispatch(self, request, *args, **kwargs):     # отправлять
        if not request.user.is_authenticated:
            return self.handle_no_permission()     
        user = self.request.user
        profile = models.Customer.objects.filter(
            user__pk=user.pk
        )
        redirect_needed = bool(profile)
        if self.redirect_on_missing_profile == True:
            redirect_needed = not redirect_needed
        if redirect_needed:
            return HttpResponseRedirect(self.profile_redirect_url)
        return super().dispatch(request, *args, **kwargs)



class CustomerCreate(CheckProfileMixin, generic.CreateView):
    profile_redirect_url = reverse_lazy('user:profile-detail')
    redirect_on_missing_profile = False
    model = models.Customer
    template_name = "user_app/profile_create.html"
    form_class = forms.CustomerCreateForm
    success_url = reverse_lazy('user:profile-detail')
    def form_valid(self, form):
        profile = form.save(commit=False)
        profile.user = self.request.user
        profile.save()
        self.object = profile
        return HttpResponseRedirect(self.get_success_url())




class CustomerUpdate(LoginRequiredMixin, generic.UpdateView):
    login_url = reverse_lazy('user:login')
    model = models.Customer
    template_name = "user_app/profile_update.html"
    form_class = forms.CustomerCreateForm
    success_url = reverse_lazy('user:profile-detail')
    def form_valid(self, form):
        profile = form.save(commit=False)
        profile.user = self.request.user
        profile.save()
        self.object = profile
        return HttpResponseRedirect(self.get_success_url())



class CustomerDetail(CheckProfileMixin, LoginRequiredMixin, generic.DetailView):
    profile_redirect_url = reverse_lazy('user:profile-create')
    login_url = reverse_lazy('user:login')
    redirect_on_missing_profile = True
    template_name = "user_app/profile_detail.html"

    def get_object(self):
        user = self.request.user
        profile = models.Customer.objects.filter(
            user__pk=user.pk
        )
        print(profile)
        if profile:
            profile = profile[0]
        else:
            profile = models.Customer.objects.create(
                user=user,
                email = '',
                first_name = '',
                last_name = '',
                phone = '',
                address='',
                additional_info = '',
                group = '',
            )
        return profile

src/user_app/templates/user_app/login.html
{% extends 'auth_base.html' %}


{% block MAIN_CONTENT %}

{% if form.errors %}
<p>Ваше имя пользователя и пароль не совпадают. Попробуйте еще раз.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>У вашей учетной записи нет доступа к этой странице.
         Чтобы продолжить, войдите в систему с учетной записью,
          у которой есть доступ.</p>
    {% else %}
    <p>Пожалуйста, войдите, чтобы увидеть эту страницу.</p>
    {% endif %}
{% endif %}

<form method="post" action="">   {# action="{% url 'login' %}" #}
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="Авторизоваться">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you set up the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Востановить пароль?</a></p> #}

{% endblock MAIN_CONTENT %}

src/user_app/templates/user_app/login_entrance.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block MAIN_CONTENT %}
<br>
<br>
    <h2>Вход</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }} 
        <button type="submit">Войти</button>
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}


{% endblock MAIN_CONTENT %}

src/user_app/templates/user_app/personalpage_list.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}

{% if user.is_authenticated %} 
<br>
<br>
<h1>Вы авторизованный пользователь: {{ user }} </h1>
<br>
<br>
    <th><button type="button" class="btn btn-outline-info"><a href="{% url 'user:logout' %}">Выход из профиля</a></button></th>
    <th><button type="button" class="btn btn-outline-info"><a href="{% url 'user:profile-detail' %}">Просмотр профиля</a></button></th>
    <th><button type="button" class="btn btn-outline-info"><a href="{% url 'orders:order-status' %}">Статус заказа</a></button></th>
    
{% else %}
<br>
<br>
<h1>Вы не авторизованный пользователь.</h1>
<br>
<br>
    <th><button type="button" class="btn btn-outline-info"><a href="{% url 'user:registration' %}">Регистрация нового пользователя</a></button></th>
    <th><button type="button" class="btn btn-outline-info"><a href="{% url 'user:login_entrance' %}">Войти в свой профиль</a></button></th>


{% endif %}



{% endblock MAIN_CONTENT %}

src/user_app/templates/user_app/profile_create.html
{% extends 'auth_base.html' %}
{% load crispy_forms_tags %}

{% block MAIN_CONTENT %}
<br>
<h3>Создание профиля</h3>

<h1 class="mt-5">{{ page_title }}</h1>
  <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }} 
            <button type="submit" class="btn btn-outline-primary">Сохранить</button>   

    </form> 

{% endblock MAIN_CONTENT %}

src/user_app/templates/user_app/profile_detail.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}
<br>
<br>

<h1></h1>

<h1>Твой профиль: {{user}}</h1>
<br>

<table class="table table-striped">
    <tr>
        <th>Электронная почта</th><th>{{ object.email }}</th>
    </tr>
    <tr>
        <th>Имя</th><th>{{ object.first_name }}</th>
    </tr>
    <tr>
        <th>Фамилия</th><th>{{ object.last_name }}</th>
    </tr>
    <tr>
        <th>Телефон</th><th>{{ object.phone }}</th>
    </tr>
    <tr>
        <th>Адрес доставки</th><th>{{ object.address }}</th>
    </tr>
    <tr>
        <th>Дополнительная информация</th><th>{{ object.additional_info }}</th>
    </tr>
    
</table>
            
<th><button type="button" class="btn btn-outline-success"><a href="{% url 'user:profile-update' object.id %}">Изменить</a></button></th>
            
{% endblock MAIN_CONTENT %}

src/user_app/templates/user_app/profile_update.html
{% extends 'auth_base.html' %}
{% load crispy_forms_tags %}

{% block MAIN_CONTENT %}


<h1 class="mt-5">{{ page_title }}</h1>
  <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }} 
            <button type="submit" class="btn btn-outline-primary">Сохранить</button>   

    </form> 
               
{% endblock MAIN_CONTENT %}

src/user_app/templates/user_app/registration.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block MAIN_CONTENT %}
<br>
<br>

<h2>Регистрация нового пользователя</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }} 
    <button type="submit">Отправить</button>
  </form>



{% endblock MAIN_CONTENT %}