src/book_shop_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "book_shop"

urlpatterns = [
    path('first-page/', views.FirstPageList.as_view(), name="first-page"),
    path('search/', views.search, name='search'),    
    path('book-list/', views.BookList.as_view(), name="book-list"),
    path('book-detail/<int:pk>/', views.BookListDetail.as_view(), name="book-detail"),
    path('book-create/', views.BookCreate.as_view(), name="book-create"),
    path('book-update/<int:pk>/', views.BookUpdate.as_view(), name="book-update"),
    path('book-delete/<int:pk>/', views.BookDelete.as_view(), name="book-delete"),
    path('author-list/', views.AuthorList.as_view(), name="author-list"),
    path('author-detail/<int:pk>/', views.AuthorListDetail.as_view(), name="author-detail"),
    path('author-create/', views.AuthorCreate.as_view(), name="author-create"),
    path('author-update/<int:pk>/', views.AuthorUpdate.as_view(), name="author-update"),
    path('author-delete/<int:pk>/', views.AuthorDelete.as_view(), name="author-delete"),
    path('series-list/', views.SeriesList.as_view(), name="series-list"),
    path('series-detail/<int:pk>/', views.SeriesListDetail.as_view(), name="series-detail"),
    path('series-create/', views.SeriesCreate.as_view(), name="series-create"),
    path('series-update/<int:pk>/', views.SeriesUpdate.as_view(), name="series-update"),
    path('series-delete/<int:pk>/', views.SeriesDelete.as_view(), name="series-delete"),
    path('genre-list/', views.GenreList.as_view(), name="genre-list"),
    path('genre-detail/<int:pk>/', views.GenreListDetail.as_view(), name="genre-detail"),
    path('genre-create/', views.GenreCreate.as_view(), name="genre-create"),
    path('genre-update/<int:pk>/', views.GenreUpdate.as_view(), name="genre-update"),
    path('genre-delete/<int:pk>/', views.GenreDelete.as_view(), name="genre-delete"),
    path('publisher-list/', views.PublisherList.as_view(), name="publisher-list"),
    path('publisher-detail/<int:pk>/', views.PublisherListDetail.as_view(), name="publisher-detail"),
    path('publisher-create/', views.PublisherCreate.as_view(), name="publisher-create"),
    path('publisher-update/<int:pk>/', views.PublisherUpdate.as_view(), name="publisher-update"),
    path('publisher-delete/<int:pk>/', views.PublisherDelete.as_view(), name="publisher-delete"),
]

src/orders/urls.py
from django.urls import path, include
from . import views
from .views import order_status_list

app_name = "orders"

urlpatterns = [  
    path("cart/", views.view_cart, name="view-cart"),
    path("cart-order-list/", views.view_order_cart, name="cart-order-list"),
    path("add-item/", views.add_item_to_cart_view, name="add-item-to-cart"),
    path("evaluate/", views.evaluate_cart, name="evaluate-cart"),
    path("order-create/", views.CreateOrderGoodsView.as_view(), name="view-order-create"),
    path("created-page/", views.OrderGoodsCreateView.as_view(), name="created-page"),
    path("created-new/", views.OrderGoodsCreateViewNew.as_view(), name="created-new"),
    path('order-goods-list/', views.OrderGoodsList.as_view(), name="order-goods-list"),
    path('order-goods-update/<int:pk>/', views.OrderGoodsUpdate.as_view(), name="order-goods-update"),
    path('orderdoods-detail/<int:pk>/', views.OrderGoodsListDetail.as_view(), name="orderdoods-detail"),
    path('orderdoods-delete/<int:pk>/', views.OrderGoodsDelete.as_view(), name="orderdoods-delete"),
    path('item-in-cart-list/', views.ItemInCartList.as_view(), name="item-in-cart-list"),
    path('item-in-cart-detail/<int:pk>/', views.ItemInCartDetail.as_view(), name="item-in-cart-detail"),
    path('item-in-cart-delete/<int:pk>/', views.ItemInCartDelete.as_view(), name="item-in-cart-delete"),
    path('cart-list/', views.CartList.as_view(), name="cart-list"),
    path('cart-list-detail/<int:pk>/', views.CartListDetail.as_view(), name="cart-list-detail"),
    path('order-status/', order_status_list, name='order-status'),
    path('order-status-list/', views.OrderStatusList.as_view(), name="order-status-list"),
    path('order-status-detail/<int:pk>/', views.OrderStatusDetail.as_view(), name="order-status-detail"),
    path('order-status-create/', views.OrderStatusCreate.as_view(), name="order-status-create"),
    path('order-status-update/<int:pk>/', views.OrderStatusUpdate.as_view(), name="order-status-update"),
    path('order-status-delete/<int:pk>/', views.OrderStatusDelete.as_view(), name="order-status-delete"),
    ]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('book_shop/', include('book_shop_app.urls', namespace='book_shop')),
    path('user/', include('user_app.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('review/', include('review.urls', namespace='review')),    
]

# не для хостинга
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/forms.py
from django import forms
from . import models


class CreateOrderGoodsForm(forms.ModelForm):
    
    class Meta:
        model = models.OrderGoods
        
        fields = ['user',
                'tel',
                'address',
                ]
                  
        

src/orders/views.py
from django.forms import BaseModelForm
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from . import models, forms
from book_shop_app.models import Book
from user_app.models import Customer
from orders.models import Cart, OrderGoods, OrderStatus
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404


# 4  получить_или_создать_текущую_корзину (сохраняем в сессии)
def get_or_create_current_cart(request):
    cart_id = request.session.get('cart_id', None) # проверка в сессии ID корзинки
    if request.user.is_anonymous:
        user = None                 # если анонимный, заменяем юзера на None
    else:
        user = request.user
    cart, created = models.Cart.objects.get_or_create(     
        pk=cart_id,
        defaults={'user': user},
    )                                 # берём объект, если нет то создаем; ищем по pk
    if created:
        request.session["cart_id"] = cart.pk # создаем в сессии ID корзины
    return cart
    

# 5   получить_текущую_корзину, создать при добавл товара
def get_current_cart(request):
    cart_id = request.session.get('cart_id', None)
    cart = models.Cart.objects.filter(pk=cart_id)
    if cart:
        cart = cart[0]
    else:
        cart = bool(cart)
    return cart


# 7  добавление товара в корзину
def add_item_to_cart(request):
    item_id = int(request.POST.get("item_id"))
    book = Book.objects.get(pk=item_id)
    price = book.price
    quantity = int(request.POST.get("quantity"))
    cart = get_or_create_current_cart(request)
    item_in_cart, created = models.ItemInCart.objects.get_or_create(
        cart=cart,
        item=book,
        defaults={
            "quantity": quantity,
            "price_per_item": price
        },
    )
    if not created: # если товар был, то нужно обновить количество
        current_quality = item_in_cart.quantity
        item_in_cart.quantity = current_quality + quantity
        item_in_cart.save()


# 8   изменение в корзине количества
def evaluate_cart(request):
    if request.method == "POST":
        # print(request.POST)
        action = None
        for key, value in request.POST.items():
            # print(key, value)   
            if key[0:4] == "quan":
                update_item_in_cart(key, value)
            if key[0:4] == "acti":
                action = value
        if action == "update":
            return HttpResponseRedirect(reverse_lazy("orders:view-cart"))
        # create_order()   # создать заказ
        # сделать ограничение на созд пустого заказа
        
        return HttpResponseRedirect(reverse_lazy("orders:view-order-create"))




# 9 обновление корзины
def update_item_in_cart(key, quantity):
    item_in_cart_id = int(key.split(".")[1])
    item_in_cart = models.ItemInCart.objects.get(pk=item_in_cart_id)
    if int(quantity) == 0:
        item_in_cart.delete()
        
    else:
        item_in_cart.quantity = int(quantity)
        item_in_cart.save()








# 12 достать телефон покупателя
def get_customer_tel(user):
    if not user.is_authenticated:
        tel = None    
    else:       
        tel = user.profile.phone
    return tel



# 13 достать адрес покупателя
def get_customer_address(user):
    if not user.is_authenticated:
        address = None
    else:
        address = user.profile.address
    return address


#  достать usera
def get_create_user(user):
    if not user.is_authenticated:
        user = None
    else:
        user = user
    return user


# 2 просм корзины
def view_cart(request):
    # cart = get_or_create_current_cart(request)        # корзина будет создаваться без товара
    cart = get_current_cart(request)                    # 
    context = {'cart': cart}    
    return render(
        request,
        template_name='orders/view_cart.html',
        context=context
    )


# 3 функция созд запроса для добавл книги(товара):
def add_item_to_cart_view(request):
    if request.method == "POST":
        add_item_to_cart(request)
        #item_id = request.POST.get("item_id")
        #quantity = request.POST.get("quantity")
        
    return HttpResponseRedirect(reverse_lazy("orders:view-cart"))




# 10 # создать заказ
class CreateOrderGoodsView(generic.CreateView):
    model = models.OrderGoods, Cart
    form_class = forms.CreateOrderGoodsForm
    template_name = "orders/create_order.html"   
    success_url = reverse_lazy('orders:created-page')
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = get_current_cart(self.request)
        return context
    
    def get_form(self, **kwargs):
        form = super().get_form(**kwargs)
        form.fields['user'].initial = get_create_user(self.request.user)
        form.fields['tel'].initial = get_customer_tel(self.request.user)
        form.fields['address'].initial = get_customer_address(self.request.user)
        return form
        
            
    
    def form_valid(self, form):
        cart_id = self.request.session.get('cart_id', None)

        try:
            ordergoods = models.OrderGoods.objects.get(cart=cart_id) 
            return  HttpResponseRedirect(reverse_lazy('orders:created-page'))
          
        except models.OrderGoods.DoesNotExist:
            ordergoods = form.save(commit=False)
            ordergoods.cart = get_current_cart(self.request)
            ordergoods.save()
            self.object = ordergoods
            # print('new')
            return HttpResponseRedirect(self.get_success_url())

            

#  просм созданный заказ
def view_order_cart(request):
    # cart = get_or_create_current_cart(request)        # корзина будет создаваться без товара
    cart = get_current_cart(request)                    # 
    context = {'cart': cart}    
    return render(
        request,
        template_name='orders/cart_list.html',
        context=context
    )




# 14 
class OrderGoodsCreateView(generic.TemplateView):
    model = models.OrderGoods
    template_name = "orders/create_page.html"



class OrderGoodsCreateViewNew(generic.ListView):
    model = models.OrderGoods
    template_name = "orders/create_new.html"


class OrderGoodsList(generic.ListView):
    model = models.OrderGoods
    paginate_by = 10


class OrderGoodsListDetail(generic.DetailView):
    model = models.OrderGoods
    

class OrderGoodsUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):     #LoginRequiredMixin, PermissionRequiredMixin, 
    permission_required = 'orders.change_ordergoods'
    login_url = reverse_lazy('user:login')
    model = models.OrderGoods
    fields = ['user', 'tel', 'address', ]

class OrderGoodsDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView): #LoginRequiredMixin, PermissionRequiredMixin, 
    permission_required = 'orders.delete_ordergoods'
    login_url = reverse_lazy('user:login')
    model = models.OrderGoods
    success_url = reverse_lazy('orders:order-goods-list')



class ItemInCartList(generic.ListView):
    model = models.ItemInCart
    paginate_by = 20


class ItemInCartDetail(generic.DetailView):
    model = models.ItemInCart

class ItemInCartDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):  #LoginRequiredMixin, PermissionRequiredMixin, 
    permission_required = 'orders.delete_itemincart'
    login_url = reverse_lazy('user:login')
    model = models.ItemInCart
    success_url = reverse_lazy('orders:item-in-cart-list')






class CartList(generic.ListView):
    model = models.Cart
    paginate_by = 20

class CartListDetail(generic.DetailView):
    model = models.Cart





class OrderStatusList(generic.ListView):
    model = OrderStatus
    paginate_by = 20

class OrderStatusDetail(generic.DetailView):
    model = OrderStatus


class OrderStatusCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):       #LoginRequiredMixin, PermissionRequiredMixin, 
    #permission_required = 'book_shop_app.add_publisher'
    #login_url = reverse_lazy('user:login')
    model = models.OrderStatus
    fields = ['ordergoods', 'status',]
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Создание статуса:"
        return context


class OrderStatusUpdate(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):          #LoginRequiredMixin, PermissionRequiredMixin, 
    permission_required = 'orders.change_orderstatus'
    login_url = reverse_lazy('user:login')
    model = models.OrderStatus
    fields = ['ordergoods', 'status',]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Изменение статуса:"
        return context


class OrderStatusDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):  #LoginRequiredMixin, PermissionRequiredMixin, 
    permission_required = 'orders.delete_orderstatus'
    login_url = reverse_lazy('user:login')
    model = models.OrderStatus
    success_url = reverse_lazy('orders:order-status-list')




def order_status_list(request):
    if request.user.is_anonymous:
        user = None                 
    else:
        user = request.user   
    # Получаем все заказы и их статусы для текущего пользователя
    ordergoodss = OrderGoods.objects.filter(user=user).prefetch_related('statuses')
    return render(request, 'orders/order_status_list.html', {'ordergoodss': ordergoodss})

src/orders/templates/orders/cart_detail.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}
<br>
<br>

<h1>Корзина {{object.id}}</h1>



{% if object.cart %}
    
{% for obj in cart.all %}
        <ul>
            <li>hhjj fgg</li>
        </ul>     
    {% endfor %}

{% else %}
<h3>Нет книг у автора</h3>

{% endif %}

                
{% endblock MAIN_CONTENT %}

src/orders/templates/orders/cart_list.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}
<br>
<br>

{% if cart.order_price == 0 %}
<h2>У вас нет заказа</h2>
{% elif cart.order_price %}
<h1>Ваш заказ:</h1>
<br>
        <ul> 
            <li>Создaн - {{ cart.created }}</li> 
        </ul>
        <form action="{% url "orders:evaluate-cart" %}" method="post">
        {% csrf_token %}
        <table class="table table-hover">
            <tr>
                <th>Книга</th>
                <th>Цена за книгу</th>
                <th>Количество</th>
                <th>Итого</th>
            </tr>
            {% for item_in_cart in cart.items.all %}
            <tr>
                <td>{{ item_in_cart.item.title }}</td>
                <td>{{ item_in_cart.price_per_item }}</td>
                <td>
                    {{ item_in_cart.quantity }}
                </td>
                <td>{{ item_in_cart.price }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="3"><b>Общая стоимость:</b></td>
                <td colspan="2"><b>{{ cart.order_price }}</b></td>
            </tr>
        </table> 
        
        </form>
    
{% else %}
<h2>У вас нет заказа</h2>
{% endif %}


{% endblock MAIN_CONTENT %}

src/orders/templates/orders/create.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}

<br>
<br>
<h1>Ваш заказ создан!</h1>


{% endblock MAIN_CONTENT %}

src/orders/templates/orders/create_page.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}

<br>
<br>

<h3>Ваш заказ создан!</h3>



{% endblock MAIN_CONTENT %}

src/orders/templates/orders/itemincart_confirm_delete.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}
<br>
<br>
<h1>Вы действительно хотите удалить объект: {{ object }}?</h1>
<br>
<br>
<h3>Удаление возможно только при получении товара покупателем!!!</h3>

<form method="post">
    {% csrf_token %}
    <br>
    <button type="submit" class="btn btn-outline-danger">Удалить!!!</button>
    
</form>
                
{% endblock MAIN_CONTENT %}

src/orders/templates/orders/itemincart_detail.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}

<br>
<br>

<h1>Заказ {{object.id}}</h1>


    
            <li>{{ object.item.title }}</li>
            <li>{{ object.quantity }}</li>
            <li>{{ object.price_per_item }}</li>
            <li>{{ object.price}}</li>
                
  
{% endblock MAIN_CONTENT %}

src/orders/templates/orders/order_status_list.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}
<br>
<br>
<h1>Статусы ваших заказов:</h1>
<br>
    {% for ordergoods in ordergoodss %}
        <h3>Заказ: {{ ordergoods.id }}, от {{ ordergoods.created_at }}</h3>
        
        <h5>Статусы:</h5>
        <ul>
            {% for status in ordergoods.statuses.all %}
                <li>{{ status.status }} (обновлено: {{ status.updated_at }})</li>
            {% empty %}
                <li>Нет статусов для этого заказа.</li>
            {% endfor %}
        </ul>
    {% empty %}
        <p>У вас нет заказов.</p>
    {% endfor %}


{% endblock MAIN_CONTENT %}

src/orders/templates/orders/ordergoods_confirm_delete.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}
<br>
<br>
<h1>Вы действительно хотите удалить объект: {{ object }}?</h1>
<br>
<br>
<h3>Удаление возможно только при получении товара покупателем!!!</h3>

<form method="post">
    {% csrf_token %}
    <br>
    <button type="submit" class="btn btn-outline-danger">Удалить!!!</button>
    
</form>
                
{% endblock MAIN_CONTENT %}

src/orders/templates/orders/ordergoods_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block MAIN_CONTENT %}

<br>
<br>
<h1>Заказ № {{ object.id }}, статуз заказа: {{ object.status_order }}</h1>
<br>
<h5>для: {{ object.user }}</h5>
<h5>корзина: {{ object.cart.id }}</h5>
<h5>Телефон:  {{ object.tel }}</h5>
<h5>Адрес доставки:  {{ object.address }}</h5>
<br>
<br>
<th><button type="button" class="btn btn-outline-success"><a href="{% url 'orders:order-status-create' %}">Создать статус заказа</a></button></th>
<br>
<br>
<th><button type="button" class="btn btn-outline-success"><a href="{% url 'orders:order-goods-list' %}">Перейти к заказам</a></button></th>

{% endblock MAIN_CONTENT %}

src/orders/templates/orders/ordergoods_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block MAIN_CONTENT %}
<br>
<br>

    <h1>Изменение данных заказа</h1>
    <br>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }} 
        
    <button type="submit" class="btn btn-outline-primary">Сохранить</button>
    
    </form>   
 
    

                
{% endblock MAIN_CONTENT %}

src/orders/templates/orders/orderstatus_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block MAIN_CONTENT %}

<br>
<br>
<h1>Статус заказа для: {{ object.ordergoods }}</h1>
<br>

<h5>Статус заказа:  {{ object.status }}</h5>
<h5>Обновлено:  {{ object.updated_at }}</h5>
<br>
<br>
<th><button type="button" class="btn btn-outline-success"><a href="{% url 'orders:order-status-update' object.id %}">Изменить</a></button></th>


{% comment %} <th><button type="button" class="btn btn-outline-danger"><a href="{% url 'book_shop:author-delete' object.id %}">Удалить</a></button></th>  {% endcomment %}

{% endblock MAIN_CONTENT %}

src/orders/templates/orders/orderstatus_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block MAIN_CONTENT %}
<br>
<br>
    <h1>{{ page_title }}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }} 
    <button type="submit" class="btn btn-outline-primary">Сохранить</button>
    


    </form>   
        
                
{% endblock MAIN_CONTENT %}

src/orders/templates/orders/orderstatus_list.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}
<br>
<br>
<h5>Статусы заказов:</h5>
<br>
<table class="table table-striped">
    <tr>
        <th>ID статуса:</th>
        <th>Корзина/Заказ:</th>
        <th>Статус:</th>
        <th>Изменение:</th>
        <th>Удаление:</th>
        

    </tr>
    {% for obj in page_obj %}
    <tr>
        <th>{{ obj.ordergoods.id }}</th>
        <th>{{ obj.ordergoods }}</th>
        <th>{{ obj.status }}</th>
                
        <th><button type="button" class="btn btn-outline-success"><a href="{% url 'orders:order-status-update' obj.id %}">Изменить статус</a></button></th>
        <th><button type="button" class="btn btn-outline-danger"><a href="{% url 'orders:order-status-delete' obj.id %}">Удалить статус</a></button></th> 
            
    </tr>
    {% endfor %}
</table>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; первый</a>
            <a href="?page={{ page_obj.previous_page_number }}">предыдущий</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">следующий</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">последний &raquo;</a>
        {% endif %}
    </span>
</div>
 


{% endblock MAIN_CONTENT %}

src/orders/templates/orders/view_cart.html
{% extends 'base.html' %}


{% block MAIN_CONTENT %}

<br>
<br>
<h1>Ваша корзина:</h1>
<br>
{% if cart  %}
        <ul>
            <li>ID вашей корзины - {{ cart.id }}</li>
            <li>Создaние - {{ cart.created }}</li>
            <li>Изменение - {{ cart.updated }}</li>
        </ul>
        <h3>Книги в корзине:</h3>
        <form action="{% url "orders:evaluate-cart" %}" method="post">
        {% csrf_token %}
        <table class="table table-hover">
            <tr>
                <th>Книга</th>
                <th>Цена за книгу</th>
                <th>Количество</th>
                <th>Итого</th>
                {% comment %} <th>#</th> {% endcomment %}
            </tr>
            {% for item_in_cart in cart.items.all %}
            <tr>
                <td>{{ item_in_cart.item.title }}</td>
                <td>{{ item_in_cart.price_per_item }}</td>
                <td>
                    <div class="mb-3">           
                        <input
                        type="number"
                        name="quantity.{{item_in_cart.pk}}"
                        class="form-control"
                        step="1"
                        value="{{ item_in_cart.quantity }}"
                        min="0">    
                    </div>
                </td>
                <td>{{ item_in_cart.price }}</td>
                {% comment %} <td>#</td> {% endcomment %}
            </tr>
            {% endfor %}
            <tr>
                <td colspan="3"><b>Итоговая стоимость:</b></td>
                <td colspan="2"><b>{{ cart.order_price }}</b></td>
            </tr>
        </table> 
        {% if cart.order_price == 0 %}
        {% else %}
        <button type="submit" name="action" value="update" class="btn btn-success">Обновить</button>
        <button type="submit" name="action" value="create" class="btn btn-danger">Создать заказ</button>
        {% endif %}
        </form>

{% else %}
<h2>корзина пуста</h2>
{% endif %}



{% endblock MAIN_CONTENT %}